"map <C-F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR
set tags=tags;
set autochdir

syntax enable
syntax on
colorscheme desert
set guifont=Monospace\ 12
set fileencodings=ucs-bom,utf-8,cp936
set fileencoding=utf-8
set encoding=utf-8
set nu
set lines=35 columns=80
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set cindent

inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i
inoremap < <><ESC>i
inoremap " ""<ESC>i
inoremap ' ''<ESC>i

let mapleader=","
"autocmd InsertLeave * if pumvisible() == 0|pclose|endif
""autocmd CursorMovedI * if pumbisible() == 0|pclose|endif
source /home/bing/vundle_vimrc
